spring:
    datasource:
        url: jdbc:h2:~/bavaria;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: create-drop
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000