spring:
    datasource:
        url: jdbc:h2:~/bavaria;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: create-drop
    h2:
      console:
        enabled: true
        path: /h2-console
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000

