spring:
    datasource:
        url: jdbc:h2:~/bazos;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2-console

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
server:
  port: 8080

